-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 11:47:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ListRegalos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListRegalos` (
  `id_list` INT NOT NULL,
  `regalo` VARCHAR(45) NULL,
  `existencia` VARCHAR(45) NULL,
  `cant` VARCHAR(45) NULL,
  PRIMARY KEY (`id_list`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(90) NULL,
  `ListRegalos_id_list` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `ListRegalos_id_list`),
  INDEX `fk_Cliente_ListRegalos1_idx` (`ListRegalos_id_list` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_ListRegalos1`
    FOREIGN KEY (`ListRegalos_id_list`)
    REFERENCES `mydb`.`ListRegalos` (`id_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mesa` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id` INT NOT NULL,
  `tipoevento` VARCHAR(45) NOT NULL,
  `nom_clien` VARCHAR(45) NOT NULL,
  `nom_evento` VARCHAR(45) NULL,
  `codigo_eve` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListEveRega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListEveRega` (
  `id_evento` INT NOT NULL,
  `id_list` INT NULL,
  `id_cliente` INT NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`evento_id`),
  CONSTRAINT `fk_ListEveRega_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesa_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mesa_has_evento` (
  `mesa_id_mesa` INT NOT NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`mesa_id_mesa`, `evento_id`),
  INDEX `fk_mesa_has_evento_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_mesa_has_evento_mesa1_idx` (`mesa_id_mesa` ASC) VISIBLE,
  CONSTRAINT `fk_mesa_has_evento_mesa1`
    FOREIGN KEY (`mesa_id_mesa`)
    REFERENCES `mydb`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_has_evento_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_mesa` (
  `Cliente_id_cliente` INT NOT NULL,
  `Cliente_ListRegalos_id_list` INT NOT NULL,
  `mesa_id_mesa` INT NOT NULL,
  PRIMARY KEY (`Cliente_id_cliente`, `Cliente_ListRegalos_id_list`, `mesa_id_mesa`),
  INDEX `fk_Cliente_has_mesa_mesa1_idx` (`mesa_id_mesa` ASC) VISIBLE,
  INDEX `fk_Cliente_has_mesa_Cliente1_idx` (`Cliente_id_cliente` ASC, `Cliente_ListRegalos_id_list` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_mesa_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente` , `Cliente_ListRegalos_id_list`)
    REFERENCES `mydb`.`Cliente` (`id_cliente` , `ListRegalos_id_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_mesa_mesa1`
    FOREIGN KEY (`mesa_id_mesa`)
    REFERENCES `mydb`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
